name: Setup
description: "Setups the Elixir environment"

inputs:
  fail-on-failure:
        description: 'Should fail on dependency restoration'
        required: false
        default: false

runs:
  using: "composite"
  steps:
      - name: Install system dependencies
        shell: bash
        run: sudo apt-get install -y libsodium-dev

      - name: Install Protobuf dependencies
        shell: bash
        run: sudo apt install -y protobuf-compiler

      - name: install new protobuf
        shell: bash
        run: |
          curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v29.0/protoc-29.0-linux-x86_64.zip && \
          unzip protoc-29.0-linux-x86_64.zip -d $HOME/.local
          echo "$HOME/.local" >> $GITHUB_PATH

      - name: Set up Elixir
        id: beam
        uses: erlef/setup-beam@v1.18.2
        with:
          elixir-version: '1.17.3'
          otp-version: '27.1'

      - name: Restore dependencies cache
        id: deps-cache
        uses: actions/cache@v3.3.2
        with:
          path: |
            deps
            _build
          key: |
            mix-${{ runner.os }}-${{ steps.beam.outputs.otp-version }}-${{ steps.beam.outputs.elixir-version }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            mix-${{ runner.os }}-${{ steps.beam.outputs.otp-version }}-${{ steps.beam.outputs.elixir-version }}-${{ hashFiles('**/mix.lock') }}

      - name: Fail on dependencies cache miss
        shell: bash
        if: ${{ (inputs.fail-on-failure == 'true') && steps.deps-cache.outputs.cache-hit != 'true' }}
        run: /bin/false

      - name: Fetch dependencies
        shell: bash
        run: mix deps.get

      - name: Install Protobuf Elixir dependencies
        shell: bash
        run: mix escript.install hex protobuf --force

      - name: Build dependencies dev
        shell: bash
        run: MIX_ENV=dev mix deps.compile

      - name: Build dependencies test
        shell: bash
        run: MIX_ENV=test mix deps.compile

      - name: Restore PLT cache
        id: plt-cache
        uses: actions/cache@v3.3.2
        with:
          path: plts
          key: |
            plt-${{ runner.os }}-${{ steps.beam.outputs.otp-version }}-${{ steps.beam.outputs.elixir-version }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            plt-${{ runner.os }}-${{ steps.beam.outputs.otp-version }}-${{ steps.beam.outputs.elixir-version }}-${{ hashFiles('**/mix.lock') }}

      - name: Fail on PLT cache miss
        shell: bash
        if: ${{ (inputs.fail-on-failure == 'true') && steps.plt-cache.outputs.cache-hit != 'true' }}
        run: /bin/false
