syntax = "proto3";

package Anoma.Proto.Nock;

import "node.proto";

/*
 An input to a Nock program.
 Can either be jammed or plain-text.
 */
message Input {
  oneof input {
    bytes jammed = 1;
    string text = 2;
  }
}

/*
 Proves the given program by running it with the given inputs.
 */
message Prove {
  message Request {
    Node node = 1;

    oneof program {
      bytes jammed_program = 2;
      string text_program = 3;
    }

    repeated Input public_inputs = 4;
    repeated Input private_inputs = 5;
  }

  message Response {
    oneof result {
      Success success = 1;
      Error error = 2;
    }
  }
}

/*
 Run the given program by running it with the given inputs.
 */
message Run {
  message Request {
    Node node_info = 1;
    oneof program {
      bytes jammed_program = 2;
      string text_program = 3;
    }

    repeated Input inputs = 4;
  }

  message Response {
    oneof result {
      Success success = 1;
      Error error = 2;
    }
  }
}

/*
 A successful run or proof of a program.
 */
message Success {
  bytes result = 1;
  repeated bytes output = 2;
}

/*
 A failed run or proof of a program.
 */
message Error {
  string error = 1;
  repeated bytes output = 2;
}
