name: "Release pre built"
description: "Builds Anoma releases"
inputs:
  otp_version:
    description: "The exact OTP version (major.minor[.patch])"
runs:
  using: "composite"
  steps:
    - uses: erlef/setup-beam@v1.18.2
      if: startsWith(runner.os, 'Linux') || startsWith(runner.os, 'Windows')
      with:
        otp-version: ${{ inputs.otp_version }}
        elixir-version: "1.17.3"
    - name: Install system dependencies
      shell: bash
      if: startsWith(runner.os, 'Linux')
      run: sudo apt install -y libsodium-dev protobuf-compiler
    - name: Install system dependencies
      shell: bash
      if: startsWith(runner.os, 'macOS')
      run: brew install elixir protobuf
    - name: Install system dependencies
      shell: pwsh
      if: startsWith(runner.os, 'Windows')
      run: |
        choco install protoc
        vcpkg install libsodium
    - name: Install Elixir dependencies
      shell: bash
      run: |
        mix deps.get --force
        mix escript.install hex protobuf --force
    - name: Build Anoma release
      if: startsWith(runner.os, 'Linux') || startsWith(runner.os, 'macOS')
      shell: bash
      run: |
        export PATH="$PATH:$HOME/.mix/escripts"
        mix release
    - name: Copy shared libraries
      if: startsWith(runner.os, 'macOS')
      shell: bash
      run: ./scripts/copy-dylibs.zsh _build/dev/rel/anoma
    - name: Copy shared libraries and client
      if: startsWith(runner.os, 'Linux')
      shell: bash
      run: |
        ./scripts/copy-sos.sh _build/dev/rel/anoma
        cp ./scripts/anomac _build/dev/rel/anoma/bin/
    - name: Build Anoma release
      if: startsWith(runner.os, 'Windows')
      shell: pwsh
      run: |
        & "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\Launch-VsDevShell.ps1" -Arch amd64 -SkipAutomaticLocation
        $env:PATH += $env:USERPROFILE + '\.mix\escripts;'
        $env:INCLUDE += ';' + $env:VCPKG_INSTALLATION_ROOT + '\packages\libsodium_x64-windows\include'
        $env:LIB += ';' + $env:VCPKG_INSTALLATION_ROOT + '\packages\libsodium_x64-windows\lib'
        mix release
    - name: Compute SHA hashes
      shell: pwsh
      run: |
        cd _build/dev/rel/
        tar czf anoma.tar.gz anoma
        shasum -a 1 anoma.tar.gz > anoma.tar.gz.sha1sum
        shasum -a 256 anoma.tar.gz > anoma.tar.gz.sha256sum
