defmodule AnomaNode.MixProject do
  use Mix.Project

  def version do
    {ver, _} = Code.eval_file("version.exs", "../..")
    ver
  end

  def project do
    [
      app: :anoma_node,
      version: version(),
      build_path: "../../_build",
      config_path: "../../config/config.exs",
      deps_path: "../../deps",
      lockfile: "../../mix.lock",
      elixir: "~> 1.17",
      start_permanent: Mix.env() == :prod,
      deps: deps(),
      # Exclude from test coverage any modules generated by "typedstruct".
      test_coverage: [
        ignore_modules: [
          Anoma.Node.Logging.LoggingEvent,
          Anoma.Node.Transaction.Ordering.OrderEvent,
          Anoma.Node.Transaction.Executor.ExecutionEvent,
          Anoma.Node.Transaction.Backends.ResultEvent,
          Anoma.Node.Transaction.Backends.CompleteEvent,
          Anoma.Node.Transaction.Backends.NullifierEvent,
          Anoma.Node.Transaction.Storage.WriteEvent,
          Anoma.Node.Transaction.Mempool.Tx,
          Anoma.Node.Transaction.Mempool.TxEvent,
          Anoma.Node.Transaction.Mempool.ConsensusEvent,
          Anoma.Node.Transaction.Mempool.BlockEvent,
          Anoma.Node.Registry.Address,
          Anoma.Node.Examples.ETransport.ETcp.Context
        ]
      ]
    ]
  end

  # Run "mix help compile.app" to learn about applications.
  def application do
    [
      mod: {Anoma.Node, []},
      extra_applications: [
        :crypto,
        :debugger,
        :enacl,
        :logger,
        :mnesia,
        :runtime_tools,
        :tools
      ]
    ]
  end

  # Run "mix help deps" to learn about dependencies.
  defp deps do
    [
      {:anoma_lib, in_umbrella: true},
      {:event_broker, in_umbrella: true}
      # {:dep_from_hexpm, "~> 0.3.0"},
      # {:dep_from_git, git: "https://github.com/elixir-lang/my_dep.git", tag: "0.1.0"},
      # {:sibling_app_in_umbrella, in_umbrella: true}
    ] ++ global_deps()
  end

  def global_deps do
    {list, _} = Code.eval_file("global_deps.exs", "../..")
    list
  end
end
