defmodule NockPoly.Term do
  @moduledoc """

  I represent a term of any type which can be generated by the
  application of finitary polynomial functors -- in particular
  all finite products and coproducts.  I am a form of S-expression
  chosen to correspond to the application of polynomial functors --
  such an application produces a dependent pair of a position
  (which is effectively a constructor together with any of its
  parameters, in the context of datatypes) and a function type
  out of a type of directions (which makes the direction-type the
  index type of the fields of a record, in the context of data
  types).

  That the function from the directions is implemented as a list
  rather than a function forces each direction-type to be finite,
  which in turn means that these terms can only represent types
  generated by _finitary_ polynomial functors.

  I am parameterized on the type of my constructor so
  that different contexts may choose different representations of
  position-types.

  I may be viewed as the initial algebra of a polynomial functor.
  Specifically, for a given constructor type `ctor`, the position-type of
  that functor is `ctor x Nat`, and for each position `(c, n)`, my
  direction-type is `Fin n` (finite sets of size `n`).  (In particular it
  is itself manifestly finitary.)  We call this functor `termf` below.
  """

  @typedoc "I generate a generic polynomial term parameterized on a constructor type."
  @type termf(ctor, x) :: {ctor, [x]}

  @doc "I am the morphism-map component of the bifunctor `termf` in the constructor parameter."
  @spec termf_map_ctor((ctor1 -> ctor2), termf(ctor1, x)) :: termf(ctor2, x)
        when ctor1: term, ctor2: term, x: term
  def termf_map_ctor(fc, {c, children}) do
    {fc.(c), children}
  end

  @doc "I am the morphism-map component of the bifunctor `termf` in the recursive parameter."
  @spec termf_map((a -> b), termf(ctor, a)) :: termf(ctor, b)
        when ctor: term, a: term, b: term
  def termf_map(f, {c, children}) do
    {c, Enum.map(children, f)}
  end

  @doc "I am the bimap for the bifunctor `termf`, mapping both constructor and recursive parameters."
  @spec termf_bimap((ctor1 -> ctor2), (a -> b), termf(ctor1, a)) ::
          termf(ctor2, b)
        when ctor1: term, ctor2: term, a: term, b: term
  def termf_bimap(fc, fx, term) do
    termf_map(fx, termf_map_ctor(fc, term))
  end

  @typedoc "Type of algebras of `termf`."
  @type termalg(ctor, x) :: (termf(ctor, x) -> x)

  # A functor which generates _open_ terms -- that is, terms
  # which may contain variables drawn from a type parameter.
  @typedoc "I generate open terms:  terms of `t` potentially containing variables."
  @type termfv(ctor, v, x) :: {:tvar, v} | {:tcom, termf(ctor, x)}

  @doc "I am the morphism-map component of the trifunctor `termfv` in the constructor parameter."
  @spec termfv_map_ctor((ctor1 -> ctor2), termfv(ctor1, v, x)) ::
          termfv(ctor2, v, x)
        when ctor1: term, ctor2: term, v: term, x: term
  def termfv_map_ctor(fc, term) do
    case term do
      {:tcom, {c, children}} ->
        {:tcom, {fc.(c), children}}

      {:tvar, var} ->
        {:tvar, var}
    end
  end

  @doc "I am the morphism-map component of the trifunctor `termfv` in the variable parameter."
  @spec termfv_map_var((v -> w), termfv(ctor, v, x)) ::
          termfv(ctor, w, x)
        when ctor: term, v: term, w: term, x: term
  def termfv_map_var(fv, term) do
    case term do
      {:tcom, {c, children}} ->
        {:tcom, {c, children}}

      {:tvar, var} ->
        {:tvar, fv.(var)}
    end
  end

  @doc "I am the morphism-map component of the trifunctor `termfv` in the recursive parameter."
  @spec termfv_map((x -> y), termfv(ctor, v, x)) ::
          termfv(ctor, v, y)
        when ctor: term, v: term, x: term, y: term
  def termfv_map(fx, term) do
    case term do
      {:tcom, {c, children}} ->
        {:tcom, termf_map(fx, {c, children})}

      {:tvar, var} ->
        {:tvar, var}
    end
  end

  @doc "I am the bimap for the trifunctor `termfv`, mapping variable and recursive parameters."
  @spec termfv_bimap((v -> w), (x -> y), termfv(ctor, v, x)) ::
          termfv(ctor, w, y)
        when ctor: term, v: term, w: term, x: term, y: term
  def termfv_bimap(fv, fx, term) do
    termfv_map(fx, termfv_map_var(fv, term))
  end

  @doc "I am the trimap for the trifunctor `termfv`, mapping constructor, variable, and recursive parameters."
  @spec termfv_trimap(
          (ctor1 -> ctor2),
          (v -> w),
          (x -> y),
          termfv(ctor1, v, x)
        ) :: termfv(ctor2, w, y)
        when ctor1: term, ctor2: term, v: term, w: term, x: term, y: term
  def termfv_trimap(fc, fv, fx, term) do
    termfv_map(fx, termfv_map_var(fv, termfv_map_ctor(fc, term)))
  end

  # I am the carrier of the initial algebra of `termfv(ctor, v)`, which is
  # guaranteed to have one because it is polynomial.  I comprise open terms
  # terms like those of `t` but potentially containing variables drawn from
  # type `v`.
  #
  # Viewed as a type constructor, I am the free monad of `termf`.
  @typedoc "A generic open polynomial term parameterized on constructor and variable types."
  @type tv(ctor, v) :: {:in_tv, termfv(ctor, v, tv(ctor, v))}

  # I am the action of the initial algebra of `termfv(ctor, v)`.
  # My implementation is trivial; I am here only to make it explicit
  # that `tv` _is_ an algebra.
  #
  # The `termfv` type uses tagged variants to distinguish between variable terms
  # and constructor terms:
  #  - My application to a variable term is the unit of the
  #    free/forgetful adjunction between the category of algebras
  #    of `termfv` (on the left) and Elixir's base category (on the right)
  #  - My application to a constructor term is the action component
  #    of the object-map component of the left adjoint of that adjunction
  @spec in_tv(termfv(ctor, v, tv(ctor, v))) :: tv(ctor, v)
        when ctor: term, v: term
  def in_tv(x) do
    {:in_tv, x}
  end

  # I am the inverse of the action of of the initial algebra of
  # `termfv(ctor, v)`; I must exist because that initial algebra
  # is a fixed point of the application of `termfv`.  I correspond
  # to pattern-matching.  Being the inverse of an algebra, I am a coalgebra.
  #
  # My implementation is trivial; I am here only to make it explicit
  # that `in_tv` has an inverse.
  @spec out_tv(tv(ctor, v)) :: termfv(ctor, v, tv(ctor, v))
        when ctor: term, v: term
  def out_tv({:in_tv, x}) do
    x
  end

  @doc """
  I create a variable term of type `termfv` by wrapping a variable in the `:tvar` tag.
  """
  @spec var_termfv(v) :: {:tvar, v} when v: term
  def var_termfv(v) do
    {:tvar, v}
  end

  @doc """
  I create a constructor term of type `termfv` by wrapping a constructor and children
  in the `:tcom` tag.
  """
  @spec com_termfv(ctor, [x]) :: {:tcom, {ctor, [x]}}
        when ctor: term, x: term
  def com_termfv(ctor, children) do
    {:tcom, {ctor, children}}
  end

  @doc """
  I create a variable term of type `tv` by composing `in_tv` with `var_termfv`.
  """
  @spec var_tv(v) :: tv(ctor, v) when ctor: term, v: term
  def var_tv(v) do
    in_tv(var_termfv(v))
  end

  @doc """
  I create a constructor term of type `tv` by composing `in_tv` with `com_termfv`.
  """
  @spec com_tv(ctor, [tv(ctor, v)]) :: tv(ctor, v) when ctor: term, v: term
  def com_tv(ctor, children) do
    in_tv(com_termfv(ctor, children))
  end

  # I am the initial algebra of `termf`, which is guaranteed to have
  # one because it is polynomial.  (Its catamorphism is defined below.)
  # I can be equivalently generated (and that is what we do here, to minimize
  # the number of explicitly-recursive types) by applying the free monad to
  # the initial object (i.e. the empty type).
  #
  # Because I am an "open" term with variable type `none()` -- that is,
  # no variables -- I am the type of _closed_ terms.
  @typedoc "I am a generic polynomial term parameterized on a constructor type."
  @type t(ctor) :: tv(ctor, none())

  @typedoc "An open natural polynomial term with variables of type `v`."
  @type nat_tv(v) :: tv(non_neg_integer(), v)

  @typedoc "An open polynomial term with Elixir atom constructors and variables of type `v`."
  @type atom_tv(v) :: tv(atom(), v)

  @typedoc "An open polynomial term with Nock atom constructors and variables of type `v`."
  @type nock_atom_tv(v) :: tv(Noun.noun_atom(), v)

  @typedoc "An open polynomial term with Nock noun constructors and variables of type `v`."
  @type nock_noun_tv(v) :: tv(Noun.t(), v)

  @typedoc "A generic polynomial term with natural-number constructors."
  @type nat_term :: t(non_neg_integer())

  @typedoc "A generic polynomial term with Elixir atom constructors."
  @type atom_term :: t(atom())

  @typedoc "A generic polynomial term with Nock atom constructors."
  @type nock_atom_term :: t(Noun.noun_atom())

  @typedoc "A generic polynomial term with Nock noun constructors."
  @type nock_noun_term :: t(Noun.t())

  @doc """
  I am the `eval` universal morphism -- the elimination rule for a
  free monad -- out of `NockPoly.Term.tv`.

  I am the right adjunct of the free/forgetful adjunction between the
  category of algebras of `termf` (on the left) and Elixir's base
  category (on the right).

  In addition to an open term, `eval` takes an algebra of the `termf`
  functor and a "substitution" function which maps variables to the return
  type.

  I am implemented by translating the algebra to a slice algebra and
  delegating to `slice_eval`.
  """
  @spec eval(termalg(ctor, r), (v -> r), tv(ctor, v)) :: r
        when ctor: term, v: term, r: term
  def eval(algebra, subst, term) do
    slice_alg = %{
      ctor: fn ctor -> ctor end,
      empty: [],
      cons: fn r_term, r_list -> [r_term | r_list] end,
      nonempty: fn nelist -> nelist end,
      term: fn ctor, children -> algebra.({ctor, children}) end
    }

    slice_eval(slice_alg, subst, term)
  end

  # I am the algebra used to implement `tcmap` below.
  @spec tcmap_alg((ctor1 -> ctor2), termf(ctor1, tv(ctor2, a))) ::
          tv(ctor2, a)
        when ctor1: term, ctor2: term, a: term
  def tcmap_alg(f, {ctor, children}) do
    com_tv(f.(ctor), children)
  end

  # I am the morphism-map component of the left adjoint of the
  # free-algebra adjunction of `termfv` (the object-map component
  # is `in_tv` above).
  @spec tcmap((ctor1 -> ctor2), tv(ctor1, a)) :: tv(ctor2, a)
        when ctor1: term, ctor2: term, a: term
  def tcmap(f, x) do
    eval(&tcmap_alg(f, &1), &Function.identity/1, x)
  end

  # I am the algebra used to implement `tvmap` below.
  @spec tvmap_alg(termf(ctor, tv(ctor, b))) :: tv(ctor, b)
        when ctor: term, b: term
  def tvmap_alg({ctor, children}) do
    com_tv(ctor, children)
  end

  # I am the substitution used to implement `tvmap` below.
  @spec tvmap_subst((a -> b), a) :: tv(ctor, b)
        when ctor: term, a: term, b: term
  def tvmap_subst(f, x) do
    var_tv(f.(x))
  end

  # I am the morphism-map component of the left adjoint of the
  # free-algebra adjunction of `termfv` (the object-map component
  # is `in_tv` above).
  @spec tvmap((a -> b), tv(ctor, a)) :: tv(ctor, b)
        when ctor: term, a: term, b: term
  def tvmap(f, x) do
    eval(&tvmap_alg(&1), &tvmap_subst(f, &1), x)
  end

  @doc """
  I am the comultiplication (or "duplicate") for the free monad `tv`.

  Given a term of type `tv(ctor, v)`, I return a term of type
  `tv(ctor, tv(ctor, v))`.
  """
  @spec tv_comult(tv(ctor, v)) :: tv(ctor, tv(ctor, v))
        when ctor: term, v: term
  def tv_comult(term) do
    # Apply tvmap with a function that creates a variable term using var_tv
    tvmap(&var_tv/1, term)
  end

  @doc """
  I am the join (or multiplication) for the free monad `tv`.

  Given a term of type `tv(ctor, tv(ctor, v))`, I return a term of type
  `tv(ctor, v)` by flattening the structure.
  """
  @spec tv_mult(tv(ctor, tv(ctor, v))) :: tv(ctor, v)
        when ctor: term, v: term
  def tv_mult(term) do
    # Define an algebra for flattening nested structures
    flatten_algebra = fn {ctor, children} ->
      com_tv(ctor, children)
    end

    # For variables, use the identity function to extract the inner variable
    eval(flatten_algebra, &Function.identity/1, term)
  end

  @doc """
  I am the monadic bind for the free monad `tv`.

  The bind of a free monad implements substitution.
  """
  @spec tv_bind((v -> tv(ctor, w)), tv(ctor, v)) :: tv(ctor, w)
        when ctor: term, v: term, w: term
  def tv_bind(f, m) do
    tv_mult(tvmap(f, m))
  end

  defmodule Unreachable do
    @moduledoc """
    I contain a function expected to be unreachable, factored out as a module
    so that test coverage can ignore it.
    """

    # A helper function for the specialization of `tv` to `t` which
    # uses the `none()` variable type.  This is effectively the
    # unique possible `subst` parameter to `eval` when `v` is `none()`.
    @dialyzer {:nowarn_function, unreachable_term: 1}
    @spec unreachable_term(none()) :: no_return()
    def unreachable_term(var) do
      raise "Variable in closed term encountered: #{inspect(var)}"
    end
  end

  @doc """
  I am the catamorphism (fold) -- the universal morphism out of
  an initial algebra -- for `NockPoly.Term.t`.

  `cata(term, algebra)` recursively folds the term by applying the given
  algebra function to each constructor along with the list of results from
  folding its children.

  The algebra should be a function of type `(ctor, [r]) -> r`,
  where `ctor` is the constructor type and `r` is an arbitrary result type.
  """
  @spec cata(t(ctor), termalg(ctor, r)) :: r when ctor: term, r: term
  def cata(term, algebra) do
    eval(algebra, &Unreachable.unreachable_term/1, term)
  end

  @typedoc """
  I am a slice algebra for polynomial terms.

  I provide separate result types for:
  - `r_term`: the overall term result
  - `r_ctor`: the result for a constructor (atom/position)
  - `r_list`: the result for a list of child terms (possibly empty)
  - `r_nelist`: the result for a non-empty list of child terms

  The algebra decomposes both term structure and list structure:
  - List constructors: `empty` and `nonempty`
  - Non-empty list constructor: `cons`
  - Term constructor: `term` (constructor + children list)
  """
  @type term_slice_alg(ctor, r_term, r_ctor, r_list, r_nelist) :: %{
          ctor: (ctor -> r_ctor),
          empty: r_list,
          cons: (r_term, r_list -> r_nelist),
          nonempty: (r_nelist -> r_list),
          term: (r_ctor, r_list -> r_term)
        }

  @doc """
  I am the slice eval morphism for polynomial terms with variables.

  I recursively evaluate an open term by:
  - For variables: applying the substitution function to get `r_term`
  - For constructors: applying `ctor` to get `r_ctor`, delegating to
    `slice_eval_list` to build the children list, then applying `term`
    to get `r_term`

  I am mutually recursive with `slice_eval_list`.
  """
  @spec slice_eval(
          term_slice_alg(ctor, r_term, r_ctor, r_list, r_nelist),
          (v -> r_term),
          tv(ctor, v)
        ) :: r_term
        when ctor: term,
             v: term,
             r_term: term,
             r_ctor: term,
             r_list: term,
             r_nelist: term
  def slice_eval(slice_alg, subst, term) do
    case out_tv(term) do
      {:tvar, var} ->
        subst.(var)

      {:tcom, {ctor, children}} ->
        r_ctor = slice_alg.ctor.(ctor)
        r_list = slice_eval_list(slice_alg, subst, children)
        slice_alg.term.(r_ctor, r_list)
    end
  end

  @doc """
  I am the slice catamorphism for closed polynomial terms.

  I am `slice_eval` specialized to closed terms where the variable type is `none()`.
  """
  @spec slice_cata(
          t(ctor),
          term_slice_alg(ctor, r_term, r_ctor, r_list, r_nelist)
        ) :: r_term
        when ctor: term,
             r_term: term,
             r_ctor: term,
             r_list: term,
             r_nelist: term
  def slice_cata(term, slice_alg) do
    slice_eval(slice_alg, &Unreachable.unreachable_term/1, term)
  end

  @doc """
  I am the slice eval morphism for a list of polynomial terms with variables.

  I recursively evaluate a list of terms by:
  - For the empty list: returning `empty`
  - For a non-empty list: recursively evaluating the head with `slice_eval`,
    recursively evaluating the tail with `slice_eval_list`, combining them
    with `cons` to get `r_nelist`, then applying `nonempty` to get `r_list`

  I am mutually recursive with `slice_eval`.
  """
  @spec slice_eval_list(
          term_slice_alg(ctor, r_term, r_ctor, r_list, r_nelist),
          (v -> r_term),
          [tv(ctor, v)]
        ) :: r_list
        when ctor: term,
             v: term,
             r_term: term,
             r_ctor: term,
             r_list: term,
             r_nelist: term
  def slice_eval_list(slice_alg, subst, terms) do
    case terms do
      [] ->
        slice_alg.empty

      [head | tail] ->
        r_head = slice_eval(slice_alg, subst, head)
        r_tail = slice_eval_list(slice_alg, subst, tail)
        r_nelist = slice_alg.cons.(r_head, r_tail)
        slice_alg.nonempty.(r_nelist)
    end
  end

  @doc """
  I am the slice catamorphism for a list of closed polynomial terms.

  I am a convenience wrapper around `slice_cata` that:
  1. Recursively evaluates each term in the list to get `r_term` results
  2. Builds the list using `empty`, `cons`, and `nonempty` to get `r_list`

  This is useful when performing induction on lists of closed terms.
  """
  @spec slice_cata_list(
          [t(ctor)],
          term_slice_alg(ctor, r_term, r_ctor, r_list, r_nelist)
        ) :: r_list
        when ctor: term,
             r_term: term,
             r_ctor: term,
             r_list: term,
             r_nelist: term
  def slice_cata_list(terms, slice_alg) do
    slice_eval_list(slice_alg, &Unreachable.unreachable_term/1, terms)
  end

  @doc """
  I return the maximum depth of the term as a natural number.

  Depth is 1 for a term with no children, and 0 for a variable.
  """
  @spec depth(tv(ctor, v)) :: non_neg_integer() when ctor: term, v: term
  def depth(term) do
    eval(
      fn {_ctor, results} -> 1 + Enum.max([0 | results]) end,
      fn _var -> 0 end,
      term
    )
  end

  @doc """
  I return the total number of constructors in the term
  (a variable contains no constructors).
  """
  @spec size(tv(ctor, v)) :: non_neg_integer() when ctor: term, v: term
  def size(term) do
    eval(
      fn {_ctor, results} -> 1 + Enum.sum(results) end,
      fn _var -> 0 end,
      term
    )
  end

  defmodule MacroDefs do
    @moduledoc """
    I provide macro definitions in a separate module to distinguish them
    for the purpose of ignoring code coverage (which does not know how to
    tell whether a macro has been expanded and executed).
    """

    alias NockPoly.Term

    @doc """
    I create a variable term of type `termfv`.

    ## Examples

        iex> import NockPoly.Term.MacroDefs
        iex> tfv(42)
        {:tvar, 42}
    """
    defmacro tfv(var) do
      quote do
        Term.var_termfv(unquote(var))
      end
    end

    @doc """
    I create a constructor expression term of type `termfv` with children.

    ## Examples

        iex> import NockPoly.Term.MacroDefs
        iex> tfc(:foo, [tfv(42)])
        {:tcom, {:foo, [{:tvar, 42}]}}
    """
    defmacro tfc(ctor, children) do
      quote do
        Term.com_termfv(unquote(ctor), unquote(children))
      end
    end

    @doc """
    I create a constructor expression term of type `termfv` with no children.

    ## Examples

        iex> import NockPoly.Term.MacroDefs
        iex> tfc0(:foo)
        {:tcom, {:foo, []}}
    """
    defmacro tfc0(ctor) do
      quote do
        Term.com_termfv(unquote(ctor), [])
      end
    end

    @doc """
    I create a variable term of type `tv`.

    ## Examples

        iex> import NockPoly.Term.MacroDefs
        iex> tvv(42)
        {:in_tv, {:tvar, 42}}
    """
    defmacro tvv(var) do
      quote do
        Term.var_tv(unquote(var))
      end
    end

    @doc """
    I create a constructor expression term of type `tv` with children.

    ## Examples

        iex> import NockPoly.Term.MacroDefs
        iex> tvc(:foo, [tvv(42)])
        {:in_tv, {:tcom, {:foo, [{:in_tv, {:tvar, 42}}]}}}
    """
    defmacro tvc(ctor, children) do
      quote do
        Term.com_tv(unquote(ctor), unquote(children))
      end
    end

    @doc """
    I create a constructor expression term of type `tv` with no children.

    ## Examples

        iex> import NockPoly.Term.MacroDefs
        iex> tvc0(:foo)
        {:in_tv, {:tcom, {:foo, []}}}
    """
    defmacro tvc0(ctor) do
      quote do
        Term.com_tv(unquote(ctor), [])
      end
    end
  end

  @typedoc """
  I represent a mapping from elements in a domain to elements in a codomain.
  I am a list of non-negative integers where:
  - Length = size of domain
  - Each element = index in codomain (must be in range [0..(codomain_size-1)])

  Example: [2, 0, 1] means:
  - Domain size is 3
  - Element 0 in domain maps to element 2 in codomain
  - Element 1 in domain maps to element 0 in codomain
  - Element 2 in domain maps to element 1 in codomain
  """
  @type fin_mapping :: [non_neg_integer()]

  @doc """
  I validate that a finite mapping is valid for given domain and codomain sizes.
  """
  @spec validate_fin_mapping(
          fin_mapping(),
          non_neg_integer(),
          non_neg_integer()
        ) ::
          :ok | {:error, nonempty_list(atom())}
  def validate_fin_mapping(mapping, domain_size, codomain_size) do
    cond do
      length(mapping) != domain_size ->
        {:error, [:invalid_mapping_length]}

      Enum.any?(mapping, &(&1 >= codomain_size)) ->
        {:error, [:mapping_out_of_range]}

      true ->
        :ok
    end
  end
end
