# Push On Main/Next/Base
#
# This is the pipeline that will run for every push on main or next or base.
#
# The pipeline does the following.
# 1. Compile the source code for all environments (dev, test, prod)
# 2. Run the linter on the source code.
# 3. Run the entire test suite

name: Push On Main/Next/Base
run-name: Push on `${{ github.ref_name }}`

on:
  push:
    branches: ["main", "next", "base"]

jobs:
  compile:
    strategy:
      matrix:
        target: [dev, test, prod]
    uses: ./.github/workflows/compile.yaml
    with:
      mix-env: ${{ matrix.target }}
      elixir-version: "1.17"
      otp-version: "27.1"

  lint:
    needs: compile
    uses: ./.github/workflows/lint.yaml
    with:
      mix-env: "dev"
      elixir-version: "1.17"
      otp-version: "27.1"

  test:
    needs: compile
    uses: ./.github/workflows/test.yaml
    with:
      mix-env: "test"
      elixir-version: "1.17"
      otp-version: "27.1"
