name: Release

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  create_release:
    continue-on-error: true
    runs-on: ubuntu-22.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Create release
        run: |
          echo "Creating release..."
          gh release create \
            --repo ${{ github.repository }} \
            --title ${{ github.ref_name }} \
            ${{ github.ref_name }}

  release_pre_built:
    needs: create_release
    strategy:
      fail-fast: false
      matrix:
        include:
          - otp_version: "27.0"
            os: macos-latest
          - otp_version: "27.0"
            os: ubuntu-latest
          - otp_version: "27.0"
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 50
      - uses: ./.github/workflows/release_pre_built
        with:
          otp_version: ${{ matrix.otp_version }}

      - name: Upload Pre-built
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          cd _build/dev/rel/
          export RELEASE_NAME=anoma-${{ github.ref_name }}-${{ runner.os }}-${{ runner.arch }}
          mv anoma.tar.gz $RELEASE_NAME.tar.gz
          mv anoma.tar.gz.sha1sum $RELEASE_NAME.tar.gz.sha1sum
          mv anoma.tar.gz.sha256sum $RELEASE_NAME.tar.gz.sha256sum
          gh release upload --clobber "${{ github.ref_name }}" \
            $RELEASE_NAME.tar.gz \
            $RELEASE_NAME.tar.gz.sha{1,256}sum \
  build-docs:
    name: build docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0
        with:
          fetch-depth: 0

      - uses: ./.github/workflows/setup
        with:
          fail-on-failure: ${{ true }}

      - uses: ./.github/workflows/docs
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          release: ${{ true }}
